### ISSUE TITLE
SyntaxError: JSON.parse: Parse error

### ISSUE THREAD

**Issue by ShoreNinth** [LiYulin-s/org.kde.plasma.ypm-lyrics#3]
虽然这个小部件工作正常，但是Kde的journald日志一直被这一条记录刷屏：
`
plasmashell	file:///home/shoreninth/.local/share/plasma/plasmoids/org.kde.plasma.ypm-lyrics/contents/ui/main.qml:43: SyntaxError: JSON.parse: Parse error
`

操作系统： Arch Linux 
KDE Plasma 版本： 5.27.10
KDE 程序框架版本： 5.112.0
Qt 版本： 5.15.11
内核版本： 6.6.7-arch1-1 (64 位)
图形平台： Wayland

**Comment by LiYulin-s** [comment]
#6
